library(tidyverse)
setwd("~/Downloads/DataSets")
covidData <- read_csv("covid-data.csv")
View(covidData)
ggplot(covidData, aes(x= continent , y = total_cases), stat = "identity") + geom_point()
fcolnames(covidData)
rownames(covidData)
View(filter(covidData, continent == "N/A"))
locCont <- group_by(covidData, location, continent)
summary(locCont)
