library(tidyverse)
vehicles_original <- read_csv("/home/mikhail/Documents/Database/Project/vehicles.csv")
View(vehicles_original)
vehicles_edited <- select(vehicles_original, -2 & -5 & -16 & -18 & -21 & -24:-25) #-3
View(vehicles_edited)
View(vehicles_edited %>% count(posting_date))
View(vehicles_edited %>% count(size))
colSums(is.na(vehicles_edited))
colnames(vehicles_original)
colnames(vehicles_edited)
